discord:
  bot:
    audio:
#      outputToSpeaker: false
    command:
#      prefix: !
    token: {YOUR_BOT_TOKEN}
    wakeword:
#      audioGain: 1
#      sensitivity: 0.6

amazon:
  alexa:
#    host: https://avs-alexa-na.amazon.com
  auth:
    scope: profile

server:
  port: 3000
